name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Enable Corepack and activate pnpm from package.json
        run: |
          corepack enable
          VERSION=$(node -p "require('./package.json').packageManager.split('@')[1]")
          echo "Activating pnpm@${VERSION}"
          corepack prepare pnpm@${VERSION} --activate
          pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Test
        if: success() && hashFiles('**/jest.config.*') != ''
        run: pnpm test -- --ci
