name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install pnpm (makes `pnpm` available in PATH)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Setup Node & enable pnpm lockfile caching
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Print tool versions
        run: |
          node -v
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prisma generate
        run: pnpm prisma generate

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          DATABASE_URL: 'postgresql://user:pass@localhost:5432/db'
          DIRECT_URL: 'postgresql://user:pass@localhost:5432/db'
          AUTH_SECRET: 'devsecret'
          NEXTAUTH_URL: 'http://localhost:3000'
        run: pnpm build

      - name: Typecheck
        run: pnpm typecheck
