name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Enable Corepack (uses package.json#packageManager)
        run: |
          corepack enable
          # Activate the exact pnpm version from package.json (e.g. pnpm@10.16.0)
          corepack prepare pnpm@$(node -p "require('./package.json').packageManager.split('@')[1]") --activate
          pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      # Optional tests (auto-skip if no Jest config)
      - name: Test
        if: success() && hashFiles('**/jest.config.*') != ''
        run: pnpm test -- --ci