name: CI

on:
  push:
    branches:
      - main
      - deploy/weekly-digest-fixes
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install pnpm first so it's on PATH for later steps
      - name: Setup pnpm 10.16.0
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.0
          run_install: false

      - name: Setup Node.js 20 + pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Tool versions
        run: |
          node -v
          pnpm -v

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
