name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      NEXT_TELEMETRY_DISABLED: "1"
      # If you use Postgres in CI, set a test DB here (or use sqlite if your schema allows)
      # DATABASE_URL: postgresql://user:pass@localhost:5432/testdb

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Prisma Generate
        run: npx prisma generate

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests (Vitest)
        run: npm run test:unit

      - name: Build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: E2E (Playwright)
        run: npm run test:e2e
